.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SALVAGE\-FIEFDOM" "1" "October 2019" "" ""
.
.SH "NAME"
\fBsalvage\-fiefdom\fR \- AWS Glacier Single Archive Tool
.
.SH "SYNOPSIS"
salvage\-fiefdom [\-v|\-\-version] [\-h|\-\-help] upload <path/to/files>
.
.P
salvage\-fiefdom [\-v|\-\-version] [\-h|\-\-help] rotate
.
.P
<path/to/files> is a path to the files to flatten, compress, encrypt, and upload\.
.
.P
FIXME: Complete this section\.
.
.SH "DESCRIPTION"
\fBsalvage\-fiefdom\fR is a simple Bash application to manage a single archive file stored on AWS Glacier\.
.
.P
FIXME: Complete this section\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display short help message
.
.TP
\fB\-v\fR, \fB\-\-version\fR
Display the version number
.
.P
FIXME: Complete this section\.
.
.SH "OUTPUT"
FIXME: Complete this section\.
.
.SH "EXIT STATUS"
On success, returns \fB0\fR, otherwise non\-zero\.
.
.SH "SEE ALSO"
Project page: \fIhttps://github\.com/landonb/salvage\-fiefdom\fR
.
.SH "COPYRIGHT"
(c) 2019 Landon Bouma
.
.P
salvage\-fiefdom is released under the terms of an AGPLv3 license\.
